baseurl = "/"
LanguageCode = "ru"
title = "GreenITGlobe"
theme = "landing"
contentdir = "content-russian"
staticdir = "static"
publishdir = "ru"
relativeURLs = true

[permalinks]
    post = "/:filename"